{
    "name": "Hat Sentry — Risk Guardrails & Alerts",
    "version": "19.0.1.0.0",
    "category": "Hat Sentry",
    "summary": "Personal risk limits, breach detection, cooldown mode, enhanced alerting",
    "author": "Business Solutions For Africa",
    "website": "https://www.biz-africa.com/",
    "license": "LGPL-3",
    "depends": ["hat_sentry", "hat_sentry_binance", "mail"],
    "data": [
        "security/hat_sentry_risk_security.xml",
        "security/ir.model.access.csv",
        "data/risk_cron.xml",
        "views/risk_limit_views.xml",
        "views/risk_event_views.xml",
        "views/cooldown_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
