{
    "name": "Hat Sentry — Trading Journal",
    "version": "19.0.1.0.0",
    "category": "Hat Sentry",
    "summary": "Trading journal, decision logs, trade tracking with P&L",
    "author": "Business Solutions For Africa",
    "website": "https://www.biz-africa.com/",
    "license": "LGPL-3",
    "depends": ["hat_sentry", "mail"],
    "data": [
        "security/hat_sentry_journal_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "views/journal_tag_views.xml",
        "views/decision_log_views.xml",
        "views/trade_views.xml",
        "views/asset_extension_views.xml",
        "views/snapshot_extension_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
